/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.egcc.eureka.app.view;

import javax.swing.JInternalFrame;

/**
 *
 * @author Profesor
 */
public class MainView extends javax.swing.JFrame {

  /**
   * Creates new form MainView
   */
  public MainView() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    desktopPane = new javax.swing.JDesktopPane();
    menuBar = new javax.swing.JMenuBar();
    menuProceso = new javax.swing.JMenu();
    jMenuItem1 = new javax.swing.JMenuItem();
    jMenuItem2 = new javax.swing.JMenuItem();
    jMenuItem3 = new javax.swing.JMenuItem();
    menuTabla = new javax.swing.JMenu();
    jMenuItem8 = new javax.swing.JMenuItem();
    menuConsulta = new javax.swing.JMenu();
    menuConsultaClientes = new javax.swing.JMenuItem();
    jMenuItem5 = new javax.swing.JMenuItem();
    jMenuItem6 = new javax.swing.JMenuItem();
    menuReporte = new javax.swing.JMenu();
    menuUtil = new javax.swing.JMenu();
    jMenuItem7 = new javax.swing.JMenuItem();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("EUREKA APP");

    menuProceso.setText("Proceso");

    jMenuItem1.setText("jMenuItem1");
    menuProceso.add(jMenuItem1);

    jMenuItem2.setText("jMenuItem2");
    menuProceso.add(jMenuItem2);

    jMenuItem3.setText("jMenuItem3");
    menuProceso.add(jMenuItem3);

    menuBar.add(menuProceso);

    menuTabla.setText("Tabla");

    jMenuItem8.setText("jMenuItem8");
    menuTabla.add(jMenuItem8);

    menuBar.add(menuTabla);

    menuConsulta.setText("Consulta");

    menuConsultaClientes.setText("Clientes");
    menuConsultaClientes.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        menuConsultaClientesActionPerformed(evt);
      }
    });
    menuConsulta.add(menuConsultaClientes);

    jMenuItem5.setText("jMenuItem5");
    menuConsulta.add(jMenuItem5);

    jMenuItem6.setText("jMenuItem6");
    menuConsulta.add(jMenuItem6);

    menuBar.add(menuConsulta);

    menuReporte.setText("Reporte");
    menuBar.add(menuReporte);

    menuUtil.setText("Util");

    jMenuItem7.setText("jMenuItem7");
    menuUtil.add(jMenuItem7);

    menuBar.add(menuUtil);

    setJMenuBar(menuBar);

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 279, Short.MAX_VALUE)
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void menuConsultaClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConsultaClientesActionPerformed
    cargarFormulario(ClienteConsultas.class);
  }//GEN-LAST:event_menuConsultaClientesActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new MainView().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JDesktopPane desktopPane;
  private javax.swing.JMenuItem jMenuItem1;
  private javax.swing.JMenuItem jMenuItem2;
  private javax.swing.JMenuItem jMenuItem3;
  private javax.swing.JMenuItem jMenuItem5;
  private javax.swing.JMenuItem jMenuItem6;
  private javax.swing.JMenuItem jMenuItem7;
  private javax.swing.JMenuItem jMenuItem8;
  private javax.swing.JMenuBar menuBar;
  private javax.swing.JMenu menuConsulta;
  private javax.swing.JMenuItem menuConsultaClientes;
  private javax.swing.JMenu menuProceso;
  private javax.swing.JMenu menuReporte;
  private javax.swing.JMenu menuTabla;
  private javax.swing.JMenu menuUtil;
  // End of variables declaration//GEN-END:variables

  private void cargarFormulario(Class<?> aClass) {
    try {
      JInternalFrame view = null;
      // Buscandolo en el desktopPane
      for(JInternalFrame bean: desktopPane.getAllFrames()){
        if(aClass.isInstance(bean)){
          view = bean;
          break;
        }
      }
      // Crear el objeto si no existe
      if(view == null){
        view = (JInternalFrame) Class.forName(aClass.getName()).newInstance();
        desktopPane.add(view);
      }
      // Hacerlo visible
      view.setVisible(true);
      view.setSelected(true);
    } catch (Exception e) {
    }
  }

}
