/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package pe.egcc.app.prueba;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import pe.egcc.app.db.AccesoDB;

/**
 *
 * @author Profesor
 */
public class Prueba06 extends javax.swing.JFrame {

  /**
   * Creates new form Prueba06
   */
  public Prueba06() {
    initComponents();
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    txtCuenta = new javax.swing.JTextField();
    txtImporte = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    btnProcesar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

    jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
    jLabel1.setForeground(new java.awt.Color(51, 0, 255));
    jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
    jLabel1.setText("PROCESO RETIRO");

    jLabel2.setText("Cuenta:");

    jLabel3.setText("Importe:");

    btnProcesar.setText("Procesar");
    btnProcesar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        btnProcesarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
      .addGroup(layout.createSequentialGroup()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(layout.createSequentialGroup()
            .addGap(76, 76, 76)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
              .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(txtImporte)
              .addComponent(txtCuenta, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)))
          .addGroup(layout.createSequentialGroup()
            .addGap(96, 96, 96)
            .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addContainerGap(105, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jLabel1)
        .addGap(31, 31, 31)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(txtCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(txtImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel3))
        .addGap(18, 18, 18)
        .addComponent(btnProcesar, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(87, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void btnProcesarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcesarActionPerformed
    Connection cn = null;
    try {
      // Datos
      String cuenta = txtCuenta.getText();
      double importe = Double.parseDouble(txtImporte.getText());
      // Obtener conexión
      cn = AccesoDB.getConnection();
      //cn.setTransactionIsolation(Connection.TRANSACTION_SERIALIZABLE);
      // Inicio de Tx.
      cn.setAutoCommit(false);
      // Leer saldo
      double saldo;
      int contMov;
      String sql = "select dec_cuensaldo, int_cuencontmov "
              + "from cuenta "
              + "where chr_cuencodigo=? for update";
      PreparedStatement ps = cn.prepareStatement(sql);
      ps.setString(1, cuenta);
      ResultSet rs = ps.executeQuery();
      if(!rs.next()){
        throw new Exception("ERROR: cuenta no existe.");
      }
      saldo = rs.getDouble("dec_cuensaldo");
      contMov = rs.getInt("int_cuencontmov");
      rs.close();
      ps.close();
      Thread.currentThread().sleep(1000);
      // Verificar saldo
      if(importe > saldo){
        throw new Exception("ERROR: saldo es insuficiente.");
      }
      // Actualizar saldo
      saldo -= importe;
      contMov++;
      sql = "update cuenta set dec_cuensaldo=?, int_cuencontmov=? "
              + "where chr_cuencodigo=?";
      ps = cn.prepareStatement(sql);
      ps.setDouble(1, saldo);
      ps.setInt(2, contMov);
      ps.setString(3, cuenta);
      ps.executeUpdate();
      ps.close();
      // Registrar movimiento
      sql ="insert into movimiento(chr_cuencodigo, int_movinumero, "
              + "dtt_movifecha, chr_emplcodigo, chr_tipocodigo, "
              + "dec_moviimporte) values(?,?,SYSDATE,'0002','004',?)";
      ps = cn.prepareStatement(sql);
      ps.setString(1, cuenta);
      ps.setInt(2, contMov);
      ps.setDouble(3, importe);
      ps.executeUpdate();
      ps.close();
      // Confirmar Tx
      cn.commit();
      JOptionPane.showMessageDialog(rootPane, "Proceso ok.");
    } catch (Exception e) {
      try {
        if(cn != null) cn.rollback();
      } catch (Exception e1) {
      }
      JOptionPane.showMessageDialog(rootPane, e.getMessage());
    } finally{
      try {
        if(cn != null) cn.close();
      } catch (Exception e) {
      }
    }
  }//GEN-LAST:event_btnProcesarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
     * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(Prueba06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(Prueba06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(Prueba06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(Prueba06.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
        //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new Prueba06().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton btnProcesar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JTextField txtCuenta;
  private javax.swing.JTextField txtImporte;
  // End of variables declaration//GEN-END:variables
}
