package pe.egcc.eureka.app.view;

import java.beans.PropertyVetoException;
import java.util.List;
import pe.egcc.eureka.app.listener.PanelCriterioListener;
import pe.egcc.eureka.app.model.ClienteBean;
import pe.egcc.eureka.app.util.MyMessage;

/**
 *
 * @author Eric Gustavo Coronel Castillo
 * @blog gcoronelc.blogspot.com
 */
public class ClienteReporte extends javax.swing.JInternalFrame implements PanelCriterioListener {

  private List<ClienteBean> listaClientes;

  public ClienteReporte() {
    initComponents();
    panelCriterio.addPanelCriterioListener(this);
    panelCriterio.setBtnNuevoEnabled(false);
    panelCriterio.setBtnEditarEnabled(false);
    panelCriterio.setBtnEliminarEnabled(false);
  }

  /**
   * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    panelCriterio = new pe.egcc.eureka.app.view.PanelCriterioClientes();

    setClosable(true);
    setIconifiable(true);
    setMaximizable(true);
    setResizable(true);
    setTitle("REPORTE DE CLIENTES");
    addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
      public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
      }
      public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
        formInternalFrameOpened(evt);
      }
    });

    panelCriterio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addComponent(panelCriterio, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addComponent(panelCriterio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(0, 314, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    try {
      this.setMaximum(true);
    } catch (PropertyVetoException ex) {
    }
  }//GEN-LAST:event_formInternalFrameOpened


  // Variables declaration - do not modify//GEN-BEGIN:variables
  private pe.egcc.eureka.app.view.PanelCriterioClientes panelCriterio;
  // End of variables declaration//GEN-END:variables

  @Override
  public void onNuevaConsulta(List lista) {
    MyMessage.showInfo(this, "Pronto.");
  }

  @Override
  public void onExportarExcel() {
  }

  @Override
  public void onExportarCSV() {
  }

  @Override
  public void onNuevo() {
  }

  @Override
  public void onEditar() {
  }

  @Override
  public void onEliminar() {
  }

  @Override
  public void onSalir() {
    this.dispose();
  }
}
